#!/usr/bin/env python3
# SPDX-FileCopyrightText: : 2025 Ruike Lyu, rl8728@princeton.edu
"""
Refactored cost analysis plotting script.

Data source (important):
- This script **only plots figures** and by default reads the aggregated CSV:
  `results/scenario_analysis_f/scenario_plots/all_plot_data_costs.csv`
- That CSV is generated by `scripts/plot_value_scenario_comparison.py`:
  running `plot_value_scenario_comparison.py --file-type costs` will write
  `scenario_plots/all_plot_data_costs.csv` in the output directory, which is
  then consumed by this script to generate Fig. 3.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
from pathlib import Path
import logging

# Font settings
plt.rcParams['font.sans-serif'] = ['Helvetica', 'Arial', 'DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

# Logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def load_data(csv_path):
    """Load CSV data."""
    try:
        df = pd.read_csv(csv_path)
        logger.info(f"Successfully loaded data: {len(df)} rows")
        return df
    except Exception as e:
        logger.error(f"Failed to load CSV file: {e}")
        return None

def get_scenario_descriptions():
    """Return mapping from scenario code to description."""
    return {
        'L': 'Low',
        'M': 'Mid', 
        'H': 'High',
        'N': 'Non-constrained'
    }

def get_category_colors():
    """Return mapping from cost category to color."""
    return {
        "Non-renewable operation": "#ff8c00",
        "Non-renewable investment": "#545454",
        "Heating electrification": "#bf13a0",
        "Renewable investment": "#2fb537",
        "Transmission lines": "#6c9459",
        "Batteries": "#ace37f",
        "Long-duration storages": "#235ebc",
    }

def create_cost_comparison_plot(df, output_dir):
    """Create cost comparison plots."""
    
    # Create output directory
    plots_dir = output_dir / "scenario_plots"
    plots_dir.mkdir(parents=True, exist_ok=True)
    
    # Scenario descriptions and color mapping
    scenario_descriptions = get_scenario_descriptions()
    category_colors = get_category_colors()
    global_categories = sorted(df["Category"].dropna().unique().tolist())
    
    # Dimensions
    market_levels = ['L', 'M', 'H']
    flexibility_levels = ['L', 'M', 'H', 'N']
    demand_levels = ['L', 'M', 'H']
    
    # Figure: 3 rows (Market) x 4 columns (Flexibility)
    fig, axes = plt.subplots(3, 4, figsize=(20, 15), sharey=True)
    # fig.suptitle('Cost Changes by Market and Flexibility Scenarios', fontsize=16, fontweight='bold')
    
    # Create subplot for each Market–Flexibility combination
    for market_idx, market in enumerate(market_levels):
        for flex_idx, flexibility in enumerate(flexibility_levels):
            ax = axes[market_idx, flex_idx]
            
            # Filter data for current combination
            current_data = df[
                (df['Market'] == market) & 
                (df['Flexibility'] == flexibility)
            ]
            
            if current_data.empty:
                ax.text(0.5, 0.5, f'No data\nMarket: {market}\nFlex: {flexibility}', 
                       ha='center', va='center', transform=ax.transAxes, fontsize=20)
                continue
            
            # Group data by demand level
            demand_data = {}
            for demand in demand_levels:  # demand_levels = ['L', 'M', 'H']
                demand_subset = current_data[current_data['Demand'] == demand]
                if not demand_subset.empty:
                    demand_data[demand] = dict(zip(demand_subset['Category'], demand_subset['Value (CNY)']))
            
            if not demand_data:
                ax.text(0.5, 0.5, 'No demand data', ha='center', va='center', 
                       transform=ax.transAxes, fontsize=20)
                continue
            
            # Prepare stacked bar data in L/M/H order
            demand_names = [d for d in demand_levels if d in demand_data]  # Keep L, M, Horder
            x_pos = np.arange(len(demand_names))
            width = 0.6

            # Draw stacked bars (per-column ordering to keep positive/negative parts readable)
            bottom_pos = np.zeros(len(x_pos))  # up: cost increase (Value>0)
            bottom_neg = np.zeros(len(x_pos))  # down: cost reduction (Value<0)

            for i, demand in enumerate(demand_names):
                demand_vals = demand_data.get(demand, {})

                def _enforce_non_renewable_relative_order(categories: list[str], *, operation_above: bool) -> list[str]:
                    """
                    Force a fixed relative order between:
                    - Non-renewable operation
                    - Non-renewable investment

                    We interpret "operation above investment" as a drawing-order constraint:
                    - Positive stack (upwards): later draw = higher (above)
                    - Negative stack (downwards): earlier draw = closer to 0 (above)

                    This enforcement is applied AFTER the main magnitude-based sort so that only
                    the relative order of these two categories is affected.
                    """
                    op = "Non-renewable operation"
                    inv = "Non-renewable investment"
                    if op not in categories or inv not in categories:
                        return categories

                    cats = [c for c in categories if c not in (op, inv)]

                    # If operation_above=True:
                    # - For positive stack: draw inv then op (op later -> above)
                    # - For negative stack: draw op then inv (op earlier -> above)
                    # The caller chooses the appropriate operation_above meaning per stack.
                    if operation_above:
                        return cats + [inv, op]
                    return cats + [op, inv]

                # Cost increases: Value > 0, sort by value (larger closer to zero)
                inc_cats = sorted(
                    [c for c, v in demand_vals.items() if v > 0],
                    key=lambda c: demand_vals[c],
                    reverse=True,
                )
                # Positive axis (upwards): operation should be above investment
                inc_cats = _enforce_non_renewable_relative_order(inc_cats, operation_above=True)
                for category in inc_cats:
                    height = demand_vals[category]  # positive
                    if height == 0:
                        continue
                    color = category_colors.get(category, plt.cm.tab20(global_categories.index(category) % 20))
                    ax.bar(
                        x_pos[i],
                        height,
                        width,
                        bottom=bottom_pos[i],
                        color=color,
                        alpha=0.8,
                    )
                    bottom_pos[i] += height

                # Cost reductions: Value < 0, sort by absolute value (larger closer to zero)
                dec_cats = sorted(
                    [c for c, v in demand_vals.items() if v < 0],
                    key=lambda c: abs(demand_vals[c]),
                    reverse=True,
                )
                # Negative axis (downwards): operation above investment → draw operation earlier
                dec_cats = _enforce_non_renewable_relative_order(dec_cats, operation_above=False)
                for category in dec_cats:
                    height = demand_vals[category]  # negative
                    if height == 0:
                        continue
                    color = category_colors.get(category, plt.cm.tab20(global_categories.index(category) % 20))
                    ax.bar(
                        x_pos[i],
                        height,
                        width,
                        bottom=bottom_neg[i],
                        color=color,
                        alpha=0.8,
                    )
                    bottom_neg[i] += height  # more negative
            
            # Compute and show net value per bar
            net_values = []
            for i, demand in enumerate(demand_names):
                demand_data_dict = demand_data.get(demand, {})
                total_value = sum(demand_data_dict.values())
                net_values.append(total_value)
            
            # Show net value with the correct sign convention:
            # - net < 0 (reduction) label below with a minus sign
            # - net > 0 (addition) label above with a plus/implicit sign
            for i, (x, net_value) in enumerate(zip(x_pos, net_values)):
                if net_value < 0:
                    text_y = bottom_neg[i] - 0e9
                    va = 'top'
                else:
                    text_y = bottom_pos[i] + 5e9
                    va = 'bottom'

                value_text = f'{net_value/1e9:.0f}'
                ax.text(
                    x,
                    text_y,
                    value_text,
                    ha='center',
                    va=va,
                    fontsize=18,
                    fontweight='bold',
                )
            
            # X labels
            ax.set_xticks(x_pos)
            x_labels = [f'Demand: {d.replace("L", "Low").replace("M", "Mid").replace("H", "High")}' if i == 0 else d.replace("L", "Low").replace("M", "Mid").replace("H", "High") for i, d in enumerate(demand_names)]
            ax.set_xticklabels(x_labels, fontsize=20)
            
            # Y axis
            ax.set_ylim(-80e9, 30e9)
            y_ticks = np.arange(-80e9, 31e9, 20e9)
            y_labels = [f'{int(tick/1e9)}' for tick in y_ticks]
            ax.set_yticks(y_ticks)
            ax.set_yticklabels(y_labels, fontsize=20)
            
            # Zero line
            ax.axhline(y=0, color='black', linestyle='-', alpha=0.5, linewidth=1)
            
            # Titles and labels
            if market_idx == 0:  # show Flexibility label on top row
                ax.set_title(f'Flexibility: {scenario_descriptions[flexibility]}', 
                           fontsize=20, fontweight='bold')
            
            if flex_idx == 0:  # show Market label on leftmost column
                ax.set_ylabel(f'Market: {scenario_descriptions[market]}\nCost Change (Billion CNY)', 
                            fontsize=20, fontweight='bold')
            else:
                ax.set_ylabel('')
    
    # Legend created in the predefined color order
    legend_elements = []
    # Ordered legend using get_category_colors()
    ordered_categories = [
        "Renewable investment",
        "Non-renewable operation",
        "Non-renewable investment", 
        "Transmission lines",
        "Batteries",
        "Long-duration storages",
        "Heating electrification"
    ]
    
    for category in ordered_categories:
        if category in global_categories:  # only include categories that appear in data
            color = category_colors.get(category, plt.cm.tab20(len(legend_elements) % 20))
            legend_elements.append(plt.Rectangle((0,0),1,1, facecolor=color, 
                                               label=category, alpha=0.8))
    
    fig.legend(handles=legend_elements, loc='lower center', bbox_to_anchor=(0.5, -0.07),
               ncol=min(len(legend_elements), 4), fontsize=20, frameon=False)
    
    plt.tight_layout()
    
    # Save figure
    plot_file = plots_dir / "cost_comparison_refactored.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight', pad_inches=0.3)
    logger.info(f"Cost comparison figure saved to: {plot_file}")
    
    # plt.show()
    plt.close()

def create_summary_table(df, output_dir):
    """Create a CSV summary table for cost changes."""
    tables_dir = output_dir / "summary_tables"
    tables_dir.mkdir(parents=True, exist_ok=True)
    
    # Prepare table data
    table_data = []
    
    for scenario_code in df['Scenario_Code'].unique():
        scenario_data = df[df['Scenario_Code'] == scenario_code]
        
        if not scenario_data.empty:
            # Scenario info
            flexibility = scenario_data['Flexibility'].iloc[0]
            demand = scenario_data['Demand'].iloc[0]
            market = scenario_data['Market'].iloc[0]
            
            # Cost change per category
            category_changes = {}
            for _, row in scenario_data.iterrows():
                category = row['Category']
                value = row['Value (Billion CNY)']
                category_changes[category] = value
            
            # Top-3 categories with largest absolute change
            top_changes = sorted(category_changes.items(), key=lambda x: abs(x[1]), reverse=True)[:3]
            
            row = {
                'Scenario': scenario_code,
                'Flexibility': flexibility,
                'Demand': demand,
                'Market': market,
                'Top Category 1': f"{top_changes[0][0]}: {top_changes[0][1]:.2f}B" if len(top_changes) > 0 else "N/A",
                'Top Category 2': f"{top_changes[1][0]}: {top_changes[1][1]:.2f}B" if len(top_changes) > 1 else "N/A",
                'Top Category 3': f"{top_changes[2][0]}: {top_changes[2][1]:.2f}B" if len(top_changes) > 2 else "N/A"
            }
            table_data.append(row)
    
    if table_data:
        # DataFrame and sorting
        df_table = pd.DataFrame(table_data)
        df_table = df_table.sort_values(['Demand', 'Market'])
        
        # Save CSV
        table_file = tables_dir / "cost_summary_refactored.csv"
        df_table.to_csv(table_file, index=False)
        logger.info(f"Cost summary table saved to: {table_file}")
        
        # Print table to console
        print(f"\n=== Cost summary table ===")
        print(df_table.to_string(index=False))
    else:
        logger.warning("No data available for summary table.")

def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(description='Refactored cost analysis plotting script')
    parser.add_argument('--csv-file', 
                       default='results/scenario_analysis_f/scenario_plots/all_plot_data_costs.csv',
                       help='Path to input CSV file')
    parser.add_argument('--output', default='results/scenario_analysis_f', help='Output directory')
    
    args = parser.parse_args()
    
    logger.info("Start generating cost analysis figures.")
    logger.info(f"CSV file: {args.csv_file}")
    logger.info(f"Output directory: {args.output}")
    
    # Check CSV existence
    if not Path(args.csv_file).exists():
        logger.error(f"CSV file does not exist: {args.csv_file}")
        return
    
    # Load data
    df = load_data(args.csv_file)
    if df is None:
        logger.error("Failed to load data, aborting.")
        return
    
    # Create output directory
    output_path = Path(args.output)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Plots and tables
    logger.info("Generating cost comparison plots...")
    create_cost_comparison_plot(df, output_path)
    
    logger.info("Generating summary table...")
    create_summary_table(df, output_path)
    
    logger.info("Analysis complete.")
    logger.info(f"Results saved in: {output_path}")

if __name__ == "__main__":
    main()
