#!/usr/bin/env python3
# SPDX-FileCopyrightText: : 2025 Ruike Lyu, rl8728@princeton.edu
"""
Visualize scenario results generated by `generate_value_test_configs`.

The script produces 9 panels (3 markets × 3 demand levels); each panel shows
cost differences across flexibility scenarios relative to a non-flexible
baseline using 100% aluminum capacity as the reference.

Downstream consumer (Fig.3) note:
- This script writes an aggregated plotting table to:
  `results/scenario_analysis/scenario_plots/all_plot_data_costs.csv` (when `--file-type costs`)
- `scripts/fig_3_plot_costs_refactored.py` reads that CSV by default to render the
  cost-comparison figure. If you change `--output` here, pass the matching `--csv-file`
  path to the Fig.3 script.
"""

import logging
import os
import sys
import pandas as pd
import numpy as np
import argparse
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import re
import yaml

logger = logging.getLogger(__name__)

# Configure fonts that support both Latin and CJK characters (for portability)
plt.rcParams['font.sans-serif'] = ['SimHei', 'Arial Unicode MS', 'DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

def load_config(config_path):
    """
    Load a YAML configuration file.

    Parameters
    ----------
    config_path : str or Path
        Path to the configuration file.

    Returns
    -------
    dict
        Parsed configuration dictionary.
    """
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        return config
    except Exception as e:
        logger.error(f"Error while loading config file {config_path}: {str(e)}")
        return None

def get_base_version_from_config(config_path):
    """
    Read the base version tag from a configuration file.

    Parameters
    ----------
    config_path : str or Path
        Path to the configuration file.

    Returns
    -------
    str
        Base version string, or ``None`` if unavailable.
    """
    config = load_config(config_path)
    if config is None:
        logger.warning(f"Failed to load config file {config_path}; using default version tag.")
        return None
    
    version = config.get('version', '')
    # logger.info(f"from configuration file {config_path} Read the version number: {version}")
    return version

def find_scenario_results(results_dir, base_version):
    """
    Locate all scenario-result directories based on a base version tag.

    Parameters
    ----------
    results_dir : str
        Base results directory.
    base_version : str
        Version string used as prefix in result-folder names.

    Returns
    -------
    dict
        Mapping from 4-letter scenario code to version metadata.
    """
    results_path = Path(results_dir)
    if not results_path.exists():
        logger.error(f"Results directory does not exist: {results_dir}")
        return {}
    
    # Define all possible scenario combinations
    flexibility_levels = ['L', 'M', 'H', 'N']  # Low, Mid, High, Non-constrained
    demand_levels = ['L', 'M', 'H']  # Low, Mid, High
    market_levels = ['L', 'M', 'H']  # Low, Mid, High
    employment_letter = 'U'  # Fixed employment-transfer scenario used for comparison
    year = '2050'
    
    scenarios = {}
    
    # Create a 100p (100% capacity) configuration for every flexibility–demand–market combination
    for flexibility in flexibility_levels:
        for demand in demand_levels:
            for market in market_levels:
                scenario_code = f"{flexibility}{demand}{market}{employment_letter}"
                scenarios[scenario_code] = {}
                
                # Create metadata for the 100p (100% capacity) configuration
                version_name_100p = f"{base_version}-{scenario_code}-{year}-100p"
                version_dir_100p = results_path / f"version-{version_name_100p}"
                
                scenarios[scenario_code]['100p'] = {
                    'version_name': version_name_100p,
                    'version_dir': version_dir_100p,
                    'year': year,
                    'flexibility': flexibility,
                    'demand': demand,
                    'market': market,
                    'config_type': '100p'
                }
    
    # For the non-flexible reference, create a single baseline config per market
    # (using mid flexibility and mid demand for that market)
    
    # Assign the corresponding non-flexible baseline config to every scenario
    for flex in flexibility_levels:
        for dem in demand_levels:
            for mar in market_levels:
                full_scenario_code = f"{flex}{dem}{mar}{employment_letter}"
                if full_scenario_code in scenarios:
                    # For the non-flexible reference we use mid flexibility and mid demand,
                    # while keeping the same market level.
                    baseline_flexibility = 'M'  # mid flexibility
                    baseline_demand = 'M'  # mid demand
                    baseline_market = mar  # same market level
                    
                    baseline_scenario_code = f"{baseline_flexibility}{baseline_demand}{baseline_market}{employment_letter}"
                    
                    # Define the non-flexible baseline version associated with this market
                    version_name_non_flex = f"{base_version}-{baseline_scenario_code}-{year}-non_flexible"
                    version_dir_non_flex = results_path / f"version-{version_name_non_flex}"
                    
                    scenarios[full_scenario_code]['non_flexible'] = {
                        'version_name': version_name_non_flex,
                        'version_dir': version_dir_non_flex,
                        'year': year,
                        'flexibility': baseline_flexibility,  # baseline uses mid flexibility
                        'demand': baseline_demand,            # baseline uses mid demand
                        'market': baseline_market,            # baseline keeps the same market level
                        'config_type': 'non_flexible'
                    }
    
    # Note: scenarios sharing the same market level also share the same non-flexible baseline.
    
    return scenarios

def load_scenario_data(scenario_info, file_type='costs'):
    """
    Load data for a single scenario (100p and non-flexible variants).

    Parameters
    ----------
    scenario_info : dict
        Scenario metadata for one 4-letter code.
    file_type : str
        File type to load: ``'costs'`` or ``'capacities'``.

    Returns
    -------
    dict
        Dictionary with keys ``'100p'`` and ``'non_flexible'`` mapping to DataFrames.
    """
    data = {}
    
    for config_type, info in scenario_info.items():
        version_dir = info['version_dir']
        year = info['year']
        
        # Build path to the summary directory
        summary_dir = version_dir / 'summary' / 'postnetworks' / 'positive'
        
        if summary_dir.exists():
            # Locate the subdirectory for the given planning year
            year_dir = None
            for tag in ("FCG", "Neighbor"):
                candidate = summary_dir / f"postnetwork-ll-current+{tag}-linear2050-{year}"
                if candidate.exists():
                    year_dir = candidate
                    break
            
            if year_dir is not None and year_dir.exists():
                file_path = year_dir / f"{file_type}.csv"
                if file_path.exists():
                    try:
                        df = load_single_csv_file(file_path)
                        if df is not None:
                            data[config_type] = df
                        else:
                            logger.warning(f"Failed to load {file_type} data for {config_type}; using empty DataFrame.")
                            # Create an empty DataFrame to preserve structure
                            data[config_type] = pd.DataFrame()
                    except Exception as e:
                        logger.warning(f"Error loading {file_type} data for {config_type}: {str(e)}; using empty DataFrame.")
                        # Create an empty DataFrame to preserve structure
                        data[config_type] = pd.DataFrame()
                else:
                    # Create an empty DataFrame to preserve structure
                    data[config_type] = pd.DataFrame()
            else:
                # Create an empty DataFrame to preserve structure
                data[config_type] = pd.DataFrame()
        else:
            # Create an empty DataFrame to preserve structure
            data[config_type] = pd.DataFrame()
    
    return data

def load_single_csv_file(file_path):
    """
    Load a single CSV file, handling both single- and multi-index formats.

    Parameters
    ----------
    file_path : Path
        CSV file path.

    Returns
    -------
    pd.DataFrame or None
        Parsed data frame, or ``None`` on failure.
    """
    try:
        # First read a few lines to infer the structure
        with open(file_path, 'r') as f:
            first_lines = [f.readline().strip() for _ in range(5)]
        
        # Detect a potential multi-index from empty second-column entries
        has_multiindex = any(',' in line and line.split(',')[1] == '' for line in first_lines)
        
        if has_multiindex:
            # Multi-index file – read all columns without dropping anything
            df = pd.read_csv(file_path, header=None)
            
            # Post-process multi-index structure
            if len(df.columns) >= 4:
                # Use the first 3 columns as a multi-index: (component, cost_type, carrier/tech)
                df.set_index([0, 1, 2], inplace=True)
                # Rename the remaining single column as the value column
                df.columns = [df.columns[0]]
                # Cast the value column to numeric
                df[df.columns[0]] = pd.to_numeric(df[df.columns[0]], errors='coerce')
            else:
                # If there are too few columns, fall back to a simpler multi-index
                df = pd.read_csv(file_path, index_col=[0, 1])
                numeric_col = df.columns[0]
                df[numeric_col] = pd.to_numeric(df[numeric_col], errors='coerce')
        else:
            # Standard single-index file
            df = pd.read_csv(file_path, index_col=0)
            # Try to cast all columns to numeric
            for col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')
        
        return df
        
    except Exception as e:
        logger.warning(f"Error while loading {file_path}: {str(e)}")
        return None

def calculate_cost_difference(costs_100p, costs_non_flex):
    """
    Compute cost differences between a 100p and a non-flexible configuration.

    Parameters
    ----------
    costs_100p : pd.DataFrame
        Cost breakdown for the 100% aluminum-capacity configuration.
    costs_non_flex : pd.DataFrame
        Cost breakdown for the associated non-flexible baseline configuration.

    Returns
    -------
    dict
        Dictionary mapping cost-category names to cost differences (100p − non_flexible).
    """
    if costs_100p is None or costs_non_flex is None:
        return {}
    
    # Filter out aluminum-related entries; here we focus on power-system costs only
    def filter_aluminum_data(df):
        if df is None or df.empty:
            return df
        
        # Create a filtered copy of the DataFrame
        filtered_df = df.copy()
        
        # Remove rows that contain 'aluminum' in any index level
        aluminum_mask = []
        for idx in filtered_df.index:
            if len(idx) >= 3:
                # Check whether any index level contains 'aluminum'
                has_aluminum = any('aluminum' in str(level).lower() for level in idx)
                aluminum_mask.append(not has_aluminum)
            else:
                aluminum_mask.append(True)
        
        return filtered_df[aluminum_mask]
    
    # Apply the aluminum filter to both datasets
    costs_100p = filter_aluminum_data(costs_100p)
    costs_non_flex = filter_aluminum_data(costs_non_flex)
    
    # Map (cost type, carrier) pairs into aggregate cost categories
    cost_category_mapping = {
        # variable cost – non-renewable technologies
        ('marginal', 'coal'): 'Non-renewable operation',
        ('marginal', 'coal power plant'): 'Non-renewable operation',
        ('marginal', 'coal cc'): 'Non-renewable operation',
        ('marginal', 'gas'): 'Non-renewable operation',
        ('marginal', 'nuclear'): 'Non-renewable operation',
        ('marginal', 'CHP coal'): 'Non-renewable operation',
        ('marginal', 'CHP gas'): 'Non-renewable operation',
        ('marginal', 'OCGT gas'): 'Non-renewable operation',
        ('marginal', 'coal boiler'): 'Non-renewable operation',
        ('marginal', 'gas boiler'): 'Non-renewable operation',
        
        # capital cost – non-renewable technologies
        ('capital', 'coal'): 'Non-renewable investment',
        ('capital', 'coal power plant'): 'Non-renewable investment',
        ('capital', 'coal cc'): 'Non-renewable investment',
        ('capital', 'gas'): 'Non-renewable investment',
        ('capital', 'nuclear'): 'Non-renewable investment',
        ('capital', 'CHP coal'): 'Non-renewable investment',
        ('capital', 'CHP gas'): 'Non-renewable investment',
        ('capital', 'OCGT gas'): 'Non-renewable investment',
        ('capital', 'coal boiler'): 'Non-renewable investment',
        ('capital', 'gas boiler'): 'Non-renewable investment',
        
        # capital cost – demand-side electrification assets
        ('capital', 'heat pump'): 'Heating electrification',
        ('capital', 'resistive heater'): 'Heating electrification',
        
        # capital cost – renewable technologies
        ('capital', 'hydro_inflow'): 'Renewable investment',
        ('capital', 'hydroelectricity'): 'Renewable investment',
        ('capital', 'offwind'): 'Renewable investment',
        ('capital', 'onwind'): 'Renewable investment',
        ('capital', 'solar'): 'Renewable investment',
        ('capital', 'solar thermal'): 'Renewable investment',
        ('capital', 'biomass'): 'Renewable investment',
        ('capital', 'biogas'): 'Renewable investment',
        
        # transmission lines
        ('capital', 'AC'): 'Transmission lines',
        
        # batteries
        ('capital', 'battery'): 'Batteries',
        ('capital', 'battery discharger'): 'Batteries',
        ('marginal', 'battery'): 'Batteries',
        ('marginal', 'battery discharger'): 'Batteries',
        
        # long-duration storage technologies
        ('capital', 'PHS'): 'Long-duration storages',
        ('capital', 'water tanks'): 'Long-duration storages',
        ('capital', 'H2'): 'Long-duration storages',
        ('capital', 'H2 CHP'): 'Long-duration storages',
        ('marginal', 'PHS'): 'Long-duration storages',
        ('marginal', 'water tanks'): 'Long-duration storages',
        ('marginal', 'H2'): 'Long-duration storages',
        ('marginal', 'H2 CHP'): 'Long-duration storages',
        ('capital', 'stations'): 'Long-duration storages',
        
        # other categories (carbon capture, synthetic fuels, etc.)
        ('capital', 'CO2 capture'): 'Non-renewable operation',
        ('marginal', 'CO2 capture'): 'Non-renewable operation',
        ('capital', 'Sabatier'): 'Non-renewable operation',
        ('marginal', 'Sabatier'): 'Non-renewable operation',
        ('capital', 'CO2'): 'Non-renewable operation',
        ('marginal', 'CO2'): 'Non-renewable operation',
        ('capital', 'DAC'): 'Non-renewable operation',
        ('marginal', 'DAC'): 'Non-renewable operation',
    }
    
    # Organize data by aggregated cost categories
    category_changes = {}
    total_change = 0
    
    # Accumulate the change for each (cost_type, carrier) combination
    for idx in costs_100p.index:
        if len(idx) >= 3:
            component_type, cost_type, carrier = idx[0], idx[1], idx[2]
            
            # Use the mapping to aggregate into broader categories
            category_key = (cost_type, carrier)
            category_name = cost_category_mapping.get(category_key, f"{cost_type} - {carrier}")
            
            if category_name not in category_changes:
                category_changes[category_name] = 0
            
            # Extract corresponding values for 100p and non-flexible
            v1_value = costs_100p.loc[idx].iloc[0]
            v2_value = 0
            
            # Find the matching entry in the non-flexible configuration
            for idx2 in costs_non_flex.index:
                if len(idx2) >= 3 and idx2[0] == component_type and idx2[1] == cost_type and idx2[2] == carrier:
                    v2_value = costs_non_flex.loc[idx2].iloc[0]
                    break
            
            # Replace NaN values by zeros to avoid propagation
            if pd.isna(v1_value):
                v1_value = 0
            if pd.isna(v2_value):
                v2_value = 0
            
            # Compute the change (100p − non_flexible, savings are positive, increases negative)
            change = v1_value - v2_value
            category_changes[category_name] += change
            total_change += change
    
    # Filter out categories that should not be shown in the plots
    exclude_categories = {
        'marginal - renewable',
        'marginal - heat pump',
        'marginal - resistive heater',
        'marginal - onwind',
        'marginal - offwind',
        'marginal - solar',
        'marginal - solar thermal',
        'marginal - biomass',
        'marginal - biogas',
        'marginal - H2',
        'marginal - H2 CHP',
    }
    
    filtered_categories = {}
    filtered_total_change = 0  # Only sum changes for the kept categories
    
    for category, change in category_changes.items():
        # Drop NaN-like and excluded categories
        if (category not in exclude_categories and 
            abs(change) > 1e-6 and 
            'nan' not in str(category).lower() and
            not pd.isna(category)):
            filtered_categories[category] = change
            filtered_total_change += change
    
    # Add the filtered total change as a separate entry
    filtered_categories['Total Change'] = filtered_total_change
    
    return filtered_categories

def generate_scenario_plots(scenarios, output_dir, file_type='costs'):
    """
    Generate comparison plots across flexibility–demand–market scenarios.

    Parameters
    ----------
    scenarios : dict
        Scenario metadata returned by ``find_scenario_results``.
    output_dir : Path
        Output directory for plots.
    file_type : str
        File type to analyze (``'costs'`` or ``'capacities'``).
    """
    # Ensure the plot-output directory exists
    plots_dir = output_dir / "scenario_plots"
    plots_dir.mkdir(parents=True, exist_ok=True)
    
    # Mapping from scenario letters to descriptive labels
    scenario_descriptions = {
        'L': 'Low',
        'M': 'Mid', 
        'H': 'High',
        'N': 'Non-constrained'
    }
    
    # EUR-to-CNY conversion rate
    EUR_TO_CNY = 7.868
    
    # Step 1: collect all scenario data and write an intermediate CSV
    all_plot_data = []
    demand_levels = ['L', 'M', 'H']
    market_levels = ['L', 'M', 'H']
    flexibility_levels = ['L', 'M', 'H', 'N']
    employment_letter = 'U'
    
    total_combinations = len(demand_levels) * len(market_levels) * len(flexibility_levels)
    logger.info(f"Start collecting plot data for {total_combinations} scenario combinations.")
    for demand in demand_levels:
        for market in market_levels:
            for flex in flexibility_levels:
                scenario_code = f"{flex}{demand}{market}{employment_letter}"
                logger.info(f"Processing scenario {scenario_code} (Flex={flex}, Demand={demand}, Market={market})")
                if scenario_code in scenarios:
                    scenario_data = load_scenario_data(scenarios[scenario_code], file_type)
                    
                    # Check that both 100p and non-flexible data are present
                    has_100p_data = '100p' in scenario_data and not scenario_data['100p'].empty
                    has_non_flex_data = 'non_flexible' in scenario_data and not scenario_data['non_flexible'].empty
                    
                    # If either dataset is missing, skip this combination silently
                    if not has_100p_data or not has_non_flex_data:
                        continue
                    
                    # Compute cost differences for this scenario pair
                    cost_diff = calculate_cost_difference(scenario_data['100p'], scenario_data['non_flexible'])
                    
                    logger.info(f"Scenario {scenario_code}: computed cost_diff of type {type(cost_diff)}.")
                    if cost_diff:
                        # Convert to CNY and drop the aggregate 'Total Change' entry
                        for k, v in cost_diff.items():
                            if k != 'Total Change':
                                if not pd.isna(v):
                                    value_cny = v * EUR_TO_CNY
                                    all_plot_data.append({
                                        'Demand': demand,
                                        'Market': market,
                                        'Flexibility': flex,
                                        'Category': k,
                                        'Value (CNY)': value_cny,
                                        'Value (Billion CNY)': value_cny / 1e9,
                                        'Scenario_Code': scenario_code
                                    })
                        added_count = len([k for k, v in cost_diff.items() if k != 'Total Change' and not pd.isna(v)])
                        logger.info(f"Scenario {scenario_code}: added {added_count} category records to plot data.")
                    else:
                        logger.warning(f"Scenario {scenario_code}: cost_diff is empty or False – skipping.")
    
    logger.info(f"Completed data collection loop; all_plot_data length: {len(all_plot_data)}")
    
    # Save the aggregated plot data
    logger.info(f"Total number of plot-data records collected: {len(all_plot_data)}")
    if not all_plot_data:
        logger.warning("No valid plot data found; cannot generate comparison figure.")
        logger.warning("Please verify that scenario result files are present and correctly loaded.")
        return
    
    all_plot_df = pd.DataFrame(all_plot_data)
    summary_plot_csv = plots_dir / f"all_plot_data_{file_type}.csv"
    all_plot_df.to_csv(summary_plot_csv, index=False)
    # Step 2: generate the comparison figures based on the CSV data

    # Create subplots for each (market, flexibility) combination
    fig, axes = plt.subplots(3, 4, figsize=(24, 16), sharey=True)
    
    # Track category colors to ensure legends match plotted colors
    global_category_colors = {}
    
    # First collect all categories that actually appear, then assign colors
    all_categories = set()
    for i, market in enumerate(market_levels):
        for j, flex in enumerate(flexibility_levels):
            current_data = all_plot_df[
                (all_plot_df['Market'] == market) & 
                (all_plot_df['Flexibility'] == flex)
            ]
            if not current_data.empty:
                for demand in demand_levels:
                    demand_data = current_data[current_data['Demand'] == demand]
                    if not demand_data.empty:
                        all_categories.update(demand_data['Category'].unique())
    
    # Hard-coded color map for key cost categories
    category_colors = {
        # variable cost-non-renewable
        "Non-renewable operation": "#ff8c00",  # coal color
        
        # capital-non-renewable
        "Non-renewable investment": "#545454",  # nuclear color
        
        # Heating electrification
        "Heating electrification": "#bf13a0",  # heat pump color
        
        # capital-renewable
        "Renewable investment": "#f9d002",  # solar color

        # Renewable investment
        "Renewable investment": "#2fb537",  # Renewable investment color

        # transmission lines
        "Transmission lines": "#6c9459",
        # batteries
        "Batteries": "#ace37f",  # battery color
        
        # long-duration storages
        "Long-duration storages": "#235ebc",
        
        # carbon capture
        "carbon capture": "#f29dae",  # CO2 color
        
        # synthetic fuels
        "Synthetic fuels": "#9850ad",  # Sabatier color

        # Renewable investment
        "Renewable investment": "#298c81",
    }
    
    # Priority for categories when ordering stacked bars
    category_priority = {
        "Renewable investment": 1,
        "Renewable investment": 2,
        "Renewable investment": 4,
        "Non-renewable operation": 5,
        "Non-renewable investment": 6,
        "Transmission lines": 7,
        "Batteries": 8,
        "Long-duration storages": 9,
        "Heating electrification": 10,
    }
    
    # Sort categories globally by priority
    def sort_key(category):
        priority = category_priority.get(category, 999)
        return priority
    
    sorted_categories = sorted(all_categories, key=sort_key)
    
    # Assign a unique color to each category (fallback to tab20 if not pre-defined)
    for cat_idx, category in enumerate(sorted_categories):
        if category in category_colors:
            color = category_colors[category]
        else:
            # Use default colormap
            color = plt.cm.tab20(cat_idx % 20)
        global_category_colors[category] = color
    
    # Configure subplot spacing using GridSpec for fine control
    from matplotlib import gridspec
    gs = gridspec.GridSpec(3, 4, figure=fig, height_ratios=[1, 1, 1], hspace=0.1, wspace=0.1)
    
    # Re-create axes using the GridSpec layout
    axes = []
    for i in range(3):
        row_axes = []
        for j in range(4):
            ax = fig.add_subplot(gs[i, j])
            row_axes.append(ax)
        axes.append(row_axes)
    axes = np.array(axes)
    
    for i, market in enumerate(market_levels):
        for j, flex in enumerate(flexibility_levels):
            ax = axes[i, j]
            
            # Filter data for the current (market, flexibility) combination
            current_data = all_plot_df[
                (all_plot_df['Market'] == market) & 
                (all_plot_df['Flexibility'] == flex)
            ]
            
            if not current_data.empty:
                # Gather data for all demand levels under this (market, flexibility)
                demand_data_dict = {}
                for demand in demand_levels:
                    demand_data = current_data[current_data['Demand'] == demand]
                    if not demand_data.empty:
                        demand_data_dict[demand] = {}
                        for _, row in demand_data.iterrows():
                            demand_data_dict[demand][row['Category']] = row['Value (CNY)']
                
                if demand_data_dict:
                    # Collect all categories that appear for this (market, flexibility)
                    all_categories = set()
                    for demand_data in demand_data_dict.values():
                        all_categories.update(demand_data.keys())
                    
                    if all_categories:
                        categories = list(all_categories)
                        demand_names = list(demand_data_dict.keys())
                        
                        # Build stacked bar plots
                        x_pos = np.arange(len(demand_names))
                        width = 0.6  # Slightly narrower bars for cleaner appearance
                        
                        # Analyze the sign (increase vs. reduction) of each category over demand levels
                        category_signs = {}
                        for category in categories:
                            signs = []
                            for demand in demand_names:
                                demand_data = demand_data_dict.get(demand, {})
                                value = demand_data.get(category, 0)
                                if value < 0:  # Cost reduction
                                    signs.append(-1)
                                elif value > 0:  # Cost increase
                                    signs.append(1)
                                else:  # No change
                                    signs.append(0)
                            category_signs[category] = signs
                        
                        # Sort by predominant sign (reduction vs. increase), then by priority
                        def sort_key(category):
                            signs = category_signs[category]
                            # Determine predominant direction: -1 (reduction), 1 (increase), 0 (mixed/none)
                            if all(s == 0 for s in signs):
                                main_direction = 0
                            else:
                                # Compute a weighted-average direction
                                total_change = sum(abs(s) for s in signs)
                                if total_change == 0:
                                    main_direction = 0
                                else:
                                    weighted_direction = sum(s * abs(s) for s in signs) / total_change
                                    main_direction = -1 if weighted_direction < -0.1 else (1 if weighted_direction > 0.1 else 0)
                            
                            # Priority (smaller numbers = higher priority)
                            priority = category_priority.get(category, 999)
                            
                            # Return (direction, priority) as the composite sort key
                            return (main_direction, priority)
                        
                        # Apply the new sorting order
                        categories = sorted(categories, key=sort_key)
                        
                        # Use the pre-defined global color mapping
                        colors = []
                        for category in categories:
                            color = global_category_colors.get(category, plt.cm.tab20(len(colors) % 20))
                            colors.append(color)
                        
                        # Build stacked positive/negative arrays for each demand level
                        positive_changes = []
                        negative_changes = []
                        
                        for demand in demand_names:
                            demand_data = demand_data_dict.get(demand, {})
                            demand_positive = []
                            demand_negative = []
                            
                            for category in categories:
                                value = demand_data.get(category, 0)
                                # Visual convention: cost reductions (negative) plotted above, increases below
                                if value < 0:  # Cost reduction (shown above the axis)
                                    demand_positive.append(abs(value))  # Take absolute value
                                    demand_negative.append(0)
                                elif value > 0:  # Cost increase (shown below the axis)
                                    demand_positive.append(0)
                                    demand_negative.append(value)
                                else:
                                    demand_positive.append(0)
                                    demand_negative.append(0)
                            
                            positive_changes.append(demand_positive)
                            negative_changes.append(demand_negative)
                        
                        # Track which categories have already been added to the legend
                        added_to_legend = set()
                        
                        # Plot positive stack (cost reductions, above the axis)
                        bottom_positive = np.zeros(len(x_pos))
                        for cat_idx, category in enumerate(categories):
                            category_values = [changes[cat_idx] for changes in positive_changes]
                            if any(val > 0 for val in category_values):
                                # Only add each category to the legend once
                                label = category if category not in added_to_legend else ""
                                ax.bar(x_pos, category_values, width, 
                                       bottom=bottom_positive,
                                       color=colors[cat_idx], 
                                       alpha=0.8,
                                       label=label)
                                bottom_positive += np.array(category_values)
                                added_to_legend.add(category)
                        
                        # Plot negative stack (cost increases, below the axis)
                        bottom_negative = np.zeros(len(x_pos))
                        for cat_idx, category in enumerate(categories):
                            category_values = [changes[cat_idx] for changes in negative_changes]
                            if any(val > 0 for val in category_values):
                                # Same legend-handling logic for the negative stack
                                label = category if category not in added_to_legend else ""
                                ax.bar(x_pos, -np.array(category_values), width,  # Use negative values
                                       bottom=bottom_negative,
                                       color=colors[cat_idx], 
                                       alpha=0.8,
                                       label=label)
                                bottom_negative += np.array(category_values)
                                added_to_legend.add(category)
                        
                        # Compute and display the net value (sum of all categories) per bar
                        net_values = []
                        for i, demand in enumerate(demand_names):
                            demand_data = demand_data_dict.get(demand, {})
                            total_value = sum(demand_data.values())
                            net_values.append(total_value)
                        
                        # Show net worth on top of stacked chart
                        for i, (x, net_value) in enumerate(zip(x_pos, net_values)):
                            # Place the label slightly above the positive stack
                            text_y = bottom_positive[i] + 5e9
                            value_text = f'{-net_value/1e9:.0f}'
                            ax.text(x, text_y, value_text, 
                                   ha='center', va='bottom' if net_value >= 0 else 'top',
                                   fontsize=10, fontweight='bold')
                        
                        # Fix the y-axis scale (10 B CNY increments, common range)
                        y_min, y_max = -20e9, 100e9
                        y_ticks = np.arange(y_min, y_max + 10e9, 10e9)
                        y_tick_labels = [f'{int(tick/1e9)}' for tick in y_ticks]
                        
                        # Explicitly set ticks and limits to avoid auto-scaling
                        ax.set_ylim(y_min, y_max)
                        ax.set_yticks(y_ticks)
                        ax.set_yticklabels(y_tick_labels, fontsize=12)
                        
                        # Disable automatic minor ticks for a cleaner look
                        ax.yaxis.set_major_locator(plt.FixedLocator(y_ticks))
                        ax.yaxis.set_minor_locator(plt.NullLocator())
                        
                        # Label x-axis as Demand: L, M, H (only the first shows the word 'Demand')
                        ax.set_xticks(x_pos)
                        x_labels = []
                        for i, demand in enumerate(demand_names):
                            if i == 0:
                                x_labels.append(f'Demand: {demand}')
                            else:
                                x_labels.append(f'{demand}')
                        ax.set_xticklabels(x_labels, fontsize=14)
                        
                        # Turn off minor ticks everywhere
                        ax.tick_params(axis='both', which='both', left=False, right=False, top=False, bottom=False)
                        ax.tick_params(axis='x', which='minor', bottom=False)
                        ax.tick_params(axis='y', which='minor', left=False)
                        
                        # Ensure that only major y-ticks are visible
                        ax.tick_params(axis='y', which='major', left=True)
                        ax.tick_params(axis='y', which='minor', left=False)
                        
                        # Only the leftmost subplot in each row shows the y-axis label
                        if j == 0:
                            ax.set_ylabel('Cost Change (Billion CNY)', fontsize=14)
                        else:
                            ax.set_ylabel('')
                        
                        # Add a horizontal zero line
                        ax.axhline(y=0, color='black', linestyle='-', alpha=0.5, linewidth=1.5)
                        
                        # Set subplot titles and side labels
                        if i == 0:  # First row: label flexibility in the title
                            ax.set_title(f'Flexibility: {scenario_descriptions[flex]}', 
                                       fontsize=14, fontweight='bold', pad=10)
                        if j == 0:  # First column: annotate market level on the left
                            ax.text(-0.2, 0.5, f'Market: {scenario_descriptions[market]}', 
                                   fontsize=14, fontweight='bold', rotation=90, 
                                   ha='center', va='center', transform=ax.transAxes)
                        
                        # Move y-axis tick labels slightly leftward on the rightmost columns
                        if j >= 2:
                            ax.tick_params(axis='y', pad=12.5)
                    else:
                        ax.text(0.5, 0.5, 'No valid data', ha='center', va='center',
                               transform=ax.transAxes, fontsize=10)
                else:
                    ax.text(0.5, 0.5, 'No valid data', ha='center', va='center',
                           transform=ax.transAxes, fontsize=10)
            else:
                ax.text(0.5, 0.5, f'No data for\nMarket:{market}, Flexibility:{flex}', ha='center', va='center',
                       transform=ax.transAxes, fontsize=10)
            

    
    # Create a global legend below the figure
    if not all_plot_df.empty and global_category_colors:
        # Build legend entries following the global category order
        legend_elements = []
        for category in sorted_categories:
            if category in global_category_colors:
                color = global_category_colors[category]
                legend_elements.append(plt.Rectangle((0,0),1,1, facecolor=color, 
                                                   label=category, alpha=0.8))
        
        # Place a shared legend below all subplots
        fig.legend(handles=legend_elements, loc='lower center', bbox_to_anchor=(0.5, -0.05),
                   ncol=min(len(legend_elements), 5), 
                   fontsize=15)
        
    plt.tight_layout()
    # plt.show()
    
    # Save the comparison figure
    plot_file = plots_dir / f"scenario_comparison_{file_type}.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight', pad_inches=0.3)
    plt.close()

def validate_scenario_matching(scenarios, file_type='costs'):
    """
    Verify the correctness of scene matching
    
    Parameters:
    -----------
    scenarios : dict
        scene information
    file_type : str
        File type
    """
    # logger.info("=== Verify scene matching correctness ===")
    
    total_scenarios = len(scenarios)
    valid_scenarios = 0
    invalid_scenarios = 0
    
    for scenario_code, scenario_info in scenarios.items():
        if len(scenario_code) == 4:
            # Check if directory exists
            dir_100p = scenario_info['100p']['version_dir']
            if 'non_flexible' not in scenario_info:
                invalid_scenarios += 1
                logger.warning(f"Scenario {scenario_code}: missing 'non_flexible' baseline metadata")
                continue

            dir_non_flex = scenario_info['non_flexible']['version_dir']
            
            if dir_100p.exists() and dir_non_flex.exists():
                valid_scenarios += 1
            else:
                invalid_scenarios += 1
                logger.warning(f"scene {scenario_code}: Directory missing")
    
    # logger.info(f"Scenario verification completed: efficient {valid_scenarios} indivual, invalid {invalid_scenarios} indivual")
    # logger.info("")

def generate_summary_table(scenarios, output_dir, file_type='costs'):
    """
    Generate a compact summary table of the dominant cost changes per scenario.

    Parameters
    ----------
    scenarios : dict
        Scenario metadata.
    output_dir : Path
        Output directory for summary CSVs.
    file_type : str
        File type being analyzed.
    """
    # Ensure output directory exists
    tables_dir = output_dir / "summary_tables"
    tables_dir.mkdir(parents=True, exist_ok=True)
    
    # EUR-to-CNY conversion rate
    EUR_TO_CNY = 7.868
    
    # Collect row data
    table_data = []
    
    for scenario_code, scenario_info in scenarios.items():
        if len(scenario_code) == 4:  # Ensure a valid 4-character scenario code
            flexibility, demand, market = scenario_code[0], scenario_code[1], scenario_code[2]
            
            # Load 100p and non-flexible cost data
            scenario_data = load_scenario_data(scenario_info, file_type)
            
            # Skip scenarios without a full pair of datasets
            has_100p_data = '100p' in scenario_data and not scenario_data['100p'].empty
            has_non_flex_data = 'non_flexible' in scenario_data and not scenario_data['non_flexible'].empty
            if not has_100p_data or not has_non_flex_data:
                continue
            
            # Compute cost differences
            cost_diff = calculate_cost_difference(scenario_data['100p'], scenario_data['non_flexible'])
            
            if cost_diff and 'Total Change' in cost_diff:
                # Note: values in cost_diff are in EUR and must be converted to CNY
                total_change = cost_diff['Total Change'] * EUR_TO_CNY

                # Convert category-level changes to CNY
                category_changes = {}
                for category, change in cost_diff.items():
                    if category != 'Total Change':
                        category_changes[category] = change * EUR_TO_CNY
                
                # Identify the three largest (by absolute value) category changes
                top_changes = sorted(category_changes.items(), key=lambda x: abs(x[1]), reverse=True)[:3]
                
                row = {
                    'Scenario': scenario_code,
                    'Flexibility': flexibility,
                    'Demand': demand,
                    'Market': market,
                    'Top Category 1': f"{top_changes[0][0]}: {top_changes[0][1]/1e9:.2f}B" if len(top_changes) > 0 else "N/A",
                    'Top Category 2': f"{top_changes[1][0]}: {top_changes[1][1]/1e9:.2f}B" if len(top_changes) > 1 else "N/A",
                    'Top Category 3': f"{top_changes[2][0]}: {top_changes[2][1]/1e9:.2f}B" if len(top_changes) > 2 else "N/A"
                }
                table_data.append(row)
            else:
                row = {
                    'Scenario': scenario_code,
                    'Flexibility': flexibility,
                    'Demand': demand,
                    'Market': market,
                    'Top Category 1': 'N/A',
                    'Top Category 2': 'N/A',
                    'Top Category 3': 'N/A'
                }
                table_data.append(row)
    
    if table_data:
        # Build and sort the summary DataFrame
        df = pd.DataFrame(table_data)
        df = df.sort_values(['Demand', 'Market'])
        
        # Save summary table
        table_file = tables_dir / f"scenario_summary_{file_type}.csv"
        df.to_csv(table_file, index=False)
        # logger.info(f"Summary table saved to: {table_file}")
        
        # Echo a human-readable representation to stdout
        print(f"\n=== {file_type.capitalize()} Summary Table ===")
        print(df.to_string(index=False))
    else:
        logger.warning("No data available to generate a scenario summary table")

def generate_raw_cost_comparison_table(scenarios, output_dir, file_type='costs'):
    """
    Generate a detailed raw-cost comparison table for all scenarios.

    For each scenario and cost category, this table stores 100p and non-flexible
    values together with their absolute and relative differences.

    Parameters
    ----------
    scenarios : dict
        Scenario metadata.
    output_dir : Path
        Output directory.
    file_type : str
        File type being analyzed.
    """
    # Ensure output directory exists
    tables_dir = output_dir / "raw_cost_tables"
    tables_dir.mkdir(parents=True, exist_ok=True)
    
    # Collect row-wise data
    table_data = []
    
    for scenario_code, scenario_info in scenarios.items():
        if len(scenario_code) == 4:  # Ensure a valid 4-character scenario code
            flexibility, demand, market = scenario_code[0], scenario_code[1], scenario_code[2]
            
            # Load 100p and non-flexible cost data
            scenario_data = load_scenario_data(scenario_info, file_type)
            
            # Skip scenarios without a full pair of datasets
            has_100p_data = '100p' in scenario_data and not scenario_data['100p'].empty
            has_non_flex_data = 'non_flexible' in scenario_data and not scenario_data['non_flexible'].empty
            
            if not has_100p_data or not has_non_flex_data:
                continue
            
            # Data available – build raw comparison rows
            costs_100p = scenario_data['100p']
            costs_non_flex = scenario_data['non_flexible']
            
            # Collect all distinct (cost_type, carrier) combinations
            all_categories = set()
            
            # Gather categories from 100p
            for idx in costs_100p.index:
                if len(idx) >= 3:
                    component_type, cost_type, carrier = idx[0], idx[1], idx[2]
                    category_name = f"{cost_type} - {carrier}"
                    all_categories.add(category_name)
            
            # Gather categories from non-flexible
            for idx in costs_non_flex.index:
                if len(idx) >= 3:
                    component_type, cost_type, carrier = idx[0], idx[1], idx[2]
                    category_name = f"{cost_type} - {carrier}"
                    all_categories.add(category_name)
            
            # Create one row per category
            for category in sorted(all_categories):
                cost_type, carrier = category.split(" - ", 1)
                
                # Extract 100p value
                value_100p = 0
                for idx in costs_100p.index:
                    if len(idx) >= 3 and idx[1] == cost_type and idx[2] == carrier:
                        value_100p = costs_100p.loc[idx].iloc[0]
                        if pd.isna(value_100p):
                            value_100p = 0
                        break
                
                # Extract non-flexible value
                value_non_flex = 0
                for idx in costs_non_flex.index:
                    if len(idx) >= 3 and idx[1] == cost_type and idx[2] == carrier:
                        value_non_flex = costs_non_flex.loc[idx].iloc[0]
                        if pd.isna(value_non_flex):
                            value_non_flex = 0
                        break
                
                # Compute absolute and relative differences
                difference = value_100p - value_non_flex
                
                # Append to table_data
                row = {
                    'Scenario': scenario_code,
                    'Flexibility': flexibility,
                    'Demand': demand,
                    'Market': market,
                    'Category': category,
                    'Cost_Type': cost_type,
                    'Carrier': carrier,
                    'Value_100p_EUR': value_100p,
                    'Value_100p_Billion_EUR': value_100p / 1e9,
                    'Value_Non_Flex_EUR': value_non_flex,
                    'Value_Non_Flex_Billion_EUR': value_non_flex / 1e9,
                    'Difference_EUR': difference,
                    'Difference_Billion_EUR': difference / 1e9,
                    'Difference_Percent': (difference / value_non_flex * 100) if value_non_flex != 0 else 0
                }
                table_data.append(row)
    
    if table_data:
        # Build and sort the raw-detail DataFrame
        df = pd.DataFrame(table_data)
        df = df.sort_values(['Scenario', 'Category'])
        
        # Save the raw-detail table
        table_file = tables_dir / f"raw_cost_comparison_{file_type}.csv"
        df.to_csv(table_file, index=False)
        # logger.info(f"Raw cost comparison table saved to: {table_file}")
        
        # Build a scenario-level summary table (aggregated over categories)
        summary_data = []
        for scenario in df['Scenario'].unique():
            scenario_df = df[df['Scenario'] == scenario]
            
            # Compute scenario-level totals
            total_100p = scenario_df['Value_100p_EUR'].sum()
            total_non_flex = scenario_df['Value_Non_Flex_EUR'].sum()
            total_diff = total_100p - total_non_flex
            
            # Identify the five largest category changes for this scenario
            top_changes = scenario_df.nlargest(5, 'Difference_Billion_EUR')[['Category', 'Difference_Billion_EUR']]
            top_changes_str = "; ".join([f"{row['Category']}: {row['Difference_Billion_EUR']:.2f}B" for _, row in top_changes.iterrows()])
            
            summary_row = {
                'Scenario': scenario,
                'Total_100p_Billion_EUR': total_100p / 1e9,
                'Total_Non_Flex_Billion_EUR': total_non_flex / 1e9,
                'Total_Difference_Billion_EUR': total_diff / 1e9,
                'Total_Difference_Percent': (total_diff / total_non_flex * 100) if total_non_flex != 0 else 0,
                'Top_5_Changes': top_changes_str
            }
            summary_data.append(summary_row)
        
        # Save the scenario-level summary table
        summary_df = pd.DataFrame(summary_data)
        summary_df = summary_df.sort_values('Scenario')
        summary_file = tables_dir / f"raw_cost_summary_{file_type}.csv"
        summary_df.to_csv(summary_file, index=False)
        # logger.info(f"Raw cost summary table saved to: {summary_file}")
    else:
        # No data available to build a raw cost-comparison table
        return

def main():
    """Command-line entry point for scenario-comparison plots and tables."""
    parser = argparse.ArgumentParser(
        description='Visualize scenario results generated by generate_value_test_configs.'
    )
    parser.add_argument(
        '--results-dir',
        default='results',
        help='Base results directory (default: results).',
    )
    parser.add_argument(
        '--output',
        default='results/scenario_analysis',
        help='Output directory for plots and tables.',
    )
    parser.add_argument(
        '--file-type',
        choices=['costs', 'capacities'],
        default='costs',
        help='File type to analyze (default: costs).',
    )
    parser.add_argument(
        '--config',
        default='config.yaml',
        help='Path to configuration file (default: config.yaml).',
    )
    
    args = parser.parse_args()
    
    # Set log level
    log_level = logging.INFO
    logging.basicConfig(level=log_level, format='%(levelname)s: %(message)s')
    
    # logger.info(f"Start analyzing scene results，File type: {args.file_type}")
    # logger.info(f"Results directory: {args.results_dir}")
    # logger.info(f"Output directory: {args.output}")
    # logger.info(f"Configuration file: {args.config}")
    
    # Read the base version from config
    base_version = get_base_version_from_config(args.config)
    if base_version is None:
        logger.error("Failed to obtain base version; please check the configuration file.")
        return
    
    # Discover scenario results for this base version
    scenarios = find_scenario_results(args.results_dir, base_version)
    
    if not scenarios:
        logger.error("No scenario results were found under the specified results directory.")
        return
    
    # logger.info(f"Based on baseline version {base_version} Built {len(scenarios)} scenes")
    
    # Create output directory
    output_path = Path(args.output)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Verify scene matching correctness
    # logger.info("Verify scene matching correctness...")
    validate_scenario_matching(scenarios, args.file_type)
    
    # Generate scene comparison chart
    # logger.info("Generate scene comparison chart...")
    generate_scenario_plots(scenarios, output_path, args.file_type)
    
    # Generate summary table
    # logger.info("Generate summary table...")
    generate_summary_table(scenarios, output_path, args.file_type)
    
    # Generate original cost comparison table
    # logger.info("Generate original cost comparison table...")
    generate_raw_cost_comparison_table(scenarios, output_path, args.file_type)
    
    # Print data integrity statistics
    # print_data_completeness_stats(scenarios, args.file_type)
    
    # logger.info("Analysis completed！")
    # logger.info(f"The results are saved in: {output_path}")

def print_data_completeness_stats(scenarios, file_type):
    """
    Print data integrity statistics
    
    Parameters:
    -----------
    scenarios : dict
        scene information
    file_type : str
        File type
    """

if __name__ == "__main__":
    main()
